feat: Reentrant variant of `schedStateName`
blues/sparrow-lora pull request #32
Opened 2022-03-28 22:13 UTC by zfields

2022-03-28 22:21 UTC, rayozzie requested changes
Please don't do that. 

If this is the right change, then change the base method to be reenteant and change all the callers

2022-03-28 22:24 UTC, zfields commented
That was my first instinct, but it does look a little ugly compared to the original.

2022-03-28 22:29 UTC, zfields commented
What if it were to have a default value instead of a buffer?

This would allow you to perform `JAToI()`, or a more advance lookup function before entering the function.

2022-03-29 16:04 UTC, m-mcgowan requested changes

2022-03-29 16:04 UTC, m-mcgowan commented on Application/Framework/sched.c
> +        char success_state_name[20], error_state_name[20];
Would be good with a constant for the maximum state name length.

2022-03-29 18:20 UTC, merged